### ISSUE TITLE
Problem: Travis tests are failing

### ISSUE THREAD

**Issue by mamedin** [artefactual-labs/ansible-percona#41]
The travis tests are failing since Oct 9th.

**Comment by mamedin** [comment]
The role fails on "Set the root password" secure.yml task when using ansible 2.9.1. The travis CentOS tests is using the ansible 2.9.1 version.

Seems related to the `mysql_user` ansible module, and fails when trying to connect to a clean database and using the default (root) user with unix socket method. The "Set the root password" task creates users for tcp socket connections.

See:

https://github.com/ansible/ansible/issues/65887
https://github.com/ansible/ansible/issues/55845#issuecomment-487389813

Changing the "Set the root password"  task to a shell one fixes the issue:

```
- name: "Set the root password "
  shell: |
    mysql -e "FLUSH PRIVILEGES;"
    mysql -e "CREATE USER IF NOT EXISTS 'root'@'{{ item }}' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
    mysql -e "ALTER USER IF EXISTS 'root'@'{{ item }}' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
```

**Comment by csuka** [comment]
You must update/upgrade the pymysql via pip in order for it to work. I assume python3 and pip are installed.

```yaml
  - name: install | PyMySQL 0.10.0 and the rsa plugin via pip3
    pip:
      executable: pip3
      name: "{{ item }}"
    loop:
      - PyMySQL==0.10.0
      - PyMySQL[rsa]
```
